version: '3.8'
services:
  api:
    container_name: api
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=${PORT}
    ports:
      - ${PORT}:${PORT}
    env_file:
      - ./.env
    depends_on:
      - postgres
    
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    command:
      - -p ${POSTGRES_PORT}
    volumes:
      - postgres_data:/data/db/

volumes: 
 postgres_data: {}